# Generated by Django 3.1.1 on 2020-09-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='true', upload_to='image/post'),
        ),
    ]
